[tool.poetry]
name = "superautosim"
version = "0.1.0"
description = "Simulator for Super Auto Pets"
authors = ["JorVLP <47005135+JorVLP@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "sapai" }
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.3"

# optional dependencies
torch = { version = "^1.12.1", optional = true }
graphviz = { version = "^0.20.1", optional = true }

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
ipykernel = "^6.16.0"

[tool.poetry.extras]
torch = ["torch"]
graphviz = ["graphviz"]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
