name: Test

on: 
  push: 
    branches:
      - "main"
  pull_request: 
  workflow_dispatch: 

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with: 
          src: "./sapai ./tests"
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install poetry
        python -m poetry install

    - name: Run tests
      run: |
        python -m poetry run python -m unittest discover tests
